In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9581, 7576, 4186, 8675],
 [9581, 7576, 4186, 8612],
 [9581, 4709, 4186, 9202],
 [6197, 6265, 375, 5978, 4513],
 [6197, 6265, 375, 5978, 732],
 [9534, 9581, 2094, 4186, 9523],
 [650, 4401, 5681, 5978]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9581 7576 4186 8675]
 [   0    0    0    0 9581 7576 4186 8612]
 [   0    0    0    0 9581 4709 4186 9202]
 [   0    0    0 6197 6265  375 5978 4513]
 [   0    0    0 6197 6265  375 5978  732]
 [   0    0    0 9534 9581 2094 4186 9523]
 [   0    0    0    0  650 4401 5681 5978]]


In [10]:
## feature representation
dim=10

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
import warnings
warnings.filterwarnings("ignore")

model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=10, input_shape=(8,)))

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step


array([[[-0.04913319, -0.00797082, -0.0327734 , -0.00039529,
         -0.01403629,  0.03851244, -0.04123286, -0.03462777,
          0.01507298,  0.03888956],
        [-0.04913319, -0.00797082, -0.0327734 , -0.00039529,
         -0.01403629,  0.03851244, -0.04123286, -0.03462777,
          0.01507298,  0.03888956],
        [-0.04913319, -0.00797082, -0.0327734 , -0.00039529,
         -0.01403629,  0.03851244, -0.04123286, -0.03462777,
          0.01507298,  0.03888956],
        [-0.04913319, -0.00797082, -0.0327734 , -0.00039529,
         -0.01403629,  0.03851244, -0.04123286, -0.03462777,
          0.01507298,  0.03888956],
        [-0.00899843,  0.04547802,  0.0030862 , -0.02091131,
          0.00384707,  0.00036839, -0.02941915,  0.02909518,
         -0.01921059, -0.03596519],
        [-0.03940524, -0.03831446,  0.04478386,  0.04217949,
          0.04285956,  0.0453329 ,  0.02306787, -0.01061549,
          0.0131296 , -0.04510587],
        [ 0.02389393,  0.02153626,  0.03659345, -0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 9581, 7576, 4186, 8675], dtype=int32)

In [14]:
import numpy as np

model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step


array([[[-0.04913319, -0.00797082, -0.0327734 , -0.00039529,
         -0.01403629,  0.03851244, -0.04123286, -0.03462777,
          0.01507298,  0.03888956],
        [-0.04913319, -0.00797082, -0.0327734 , -0.00039529,
         -0.01403629,  0.03851244, -0.04123286, -0.03462777,
          0.01507298,  0.03888956],
        [-0.04913319, -0.00797082, -0.0327734 , -0.00039529,
         -0.01403629,  0.03851244, -0.04123286, -0.03462777,
          0.01507298,  0.03888956],
        [-0.04913319, -0.00797082, -0.0327734 , -0.00039529,
         -0.01403629,  0.03851244, -0.04123286, -0.03462777,
          0.01507298,  0.03888956],
        [-0.00899843,  0.04547802,  0.0030862 , -0.02091131,
          0.00384707,  0.00036839, -0.02941915,  0.02909518,
         -0.01921059, -0.03596519],
        [-0.03940524, -0.03831446,  0.04478386,  0.04217949,
          0.04285956,  0.0453329 ,  0.02306787, -0.01061549,
          0.0131296 , -0.04510587],
        [ 0.02389393,  0.02153626,  0.03659345, -0.0