In [18]:
from tensorflow.keras.preprocessing.text import one_hot

In [19]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [20]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [21]:
## Define the vocabulary size
voc_size=10000

In [22]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [23]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[981, 5982, 9095, 7573],
 [981, 5982, 9095, 7458],
 [981, 9984, 9095, 3697],
 [595, 9741, 3993, 4669, 6603],
 [595, 9741, 3993, 4669, 3739],
 [7186, 981, 6304, 9095, 5939],
 [6400, 8878, 4044, 4669]]

In [24]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [25]:
import numpy as np

In [26]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  981 5982 9095 7573]
 [   0    0    0    0  981 5982 9095 7458]
 [   0    0    0    0  981 9984 9095 3697]
 [   0    0    0  595 9741 3993 4669 6603]
 [   0    0    0  595 9741 3993 4669 3739]
 [   0    0    0 7186  981 6304 9095 5939]
 [   0    0    0    0 6400 8878 4044 4669]]


In [27]:
## feature representation
dim=10

In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=10, input_shape=(8,)))

model.summary()

c:\Users\Aditya Pratap\Documents\Data Analyst Bootcamp\Python\venv\Lib\site-packages\keras\src\layers\core\embedding.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 265ms/step


array([[[ 0.00666507,  0.03614885,  0.04182339,  0.00985452,
         -0.00482934, -0.02213612,  0.0400441 ,  0.01534218,
          0.00761526, -0.01424831],
        [ 0.00666507,  0.03614885,  0.04182339,  0.00985452,
         -0.00482934, -0.02213612,  0.0400441 ,  0.01534218,
          0.00761526, -0.01424831],
        [ 0.00666507,  0.03614885,  0.04182339,  0.00985452,
         -0.00482934, -0.02213612,  0.0400441 ,  0.01534218,
          0.00761526, -0.01424831],
        [ 0.00666507,  0.03614885,  0.04182339,  0.00985452,
         -0.00482934, -0.02213612,  0.0400441 ,  0.01534218,
          0.00761526, -0.01424831],
        [-0.01792043,  0.00278927, -0.00081624,  0.01750997,
          0.02187252,  0.01493635, -0.02384454, -0.01468771,
         -0.01079333, -0.01426742],
        [-0.03794247,  0.04897794,  0.03481695, -0.00615138,
          0.01504083, -0.02560512, -0.01477063, -0.02514681,
         -0.01646722,  0.0218295 ],
        [-0.01372832, -0.03525124, -0.0181297 ,  0.0

In [33]:
embedded_docs[0]

array([   0,    0,    0,    0,  981, 5982, 9095, 7573], dtype=int32)

In [37]:
import numpy as np

model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step


array([[[ 0.00666507,  0.03614885,  0.04182339,  0.00985452,
         -0.00482934, -0.02213612,  0.0400441 ,  0.01534218,
          0.00761526, -0.01424831],
        [ 0.00666507,  0.03614885,  0.04182339,  0.00985452,
         -0.00482934, -0.02213612,  0.0400441 ,  0.01534218,
          0.00761526, -0.01424831],
        [ 0.00666507,  0.03614885,  0.04182339,  0.00985452,
         -0.00482934, -0.02213612,  0.0400441 ,  0.01534218,
          0.00761526, -0.01424831],
        [ 0.00666507,  0.03614885,  0.04182339,  0.00985452,
         -0.00482934, -0.02213612,  0.0400441 ,  0.01534218,
          0.00761526, -0.01424831],
        [-0.01792043,  0.00278927, -0.00081624,  0.01750997,
          0.02187252,  0.01493635, -0.02384454, -0.01468771,
         -0.01079333, -0.01426742],
        [-0.03794247,  0.04897794,  0.03481695, -0.00615138,
          0.01504083, -0.02560512, -0.01477063, -0.02514681,
         -0.01646722,  0.0218295 ],
        [-0.01372832, -0.03525124, -0.0181297 ,  0.0